### ISSUE TITLE
Forge 3.0

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/Forge#115]
World has changed. We know live in era of .Net Core and what’s even more important in the era of .Net SDK and `dotnet` CLI tool. This means that we should think about what’s the place of Forge in this new world. Here are couple of my ideas:

* Move Forge to .Net Core
* Publish Forge as `dotnet` CLI global tool
* Remove project scaffolding part of the tool - community has embraced the `dotnet new` templates and it’s just fine. 
* Add commands to initialize Paket and FAKE in existing projects - one of the biggest advantages of Forge over `dotnet` is fact it uses Paket and FAKE for all templates which is not the case for `dotnet new`
* Add commands for changing properties in project file - this may be used for editing project files with some nice UI in editors.

**Comment by MangelMaxime** [comment]
Moving Forge to .Net Core seems a good move as we are trying to move all the F# project there I think :).

------

Can a CLI global tool be used locally ?

Like we did in the past using `clitool` via paket.

I am asking this because I am still wondering if global tool are something nice... I mean, you don't always want the same version for all your projects etc. So if user can decide, it ok :)

------

I am not sure to understand the point n°3. The idea is to provide an easy plug-in to FAKE/Paket for template that don't use one of them ? Should't we try to add the support to the template instead ? We could use conditional choice for that.

------------

Last point seems like a good idea, only if Forge do not modify what it don't understand. For example, on a Fable library forge always remove this lines:

```xml
  <!-- Add source files to "fable" folder in Nuget package -->
  <ItemGroup>
    <Content Include="*.fsproj; **\*.fs" PackagePath="fable\" />
</ItemGroup>
```

**Comment by MangelMaxime** [comment]
@JacobChang Mechanic is only about finding a correct order for the files using an algorithm. 

Here, I think it more about providing a tool to move up/down a file, add/remove properties to the *proj etc.

**Comment by JacobChang** [comment]
@MangelMaxime I see, I hope we don't fall into the npm trap, too many tools for related task.

**Comment by Krzysztof-Cieslak** [comment]
The world has changed, even more, Forge will be just small utility used under the hood by Ionide to manipulate project files (move/add files)
